### PR TITLE
fix: path replacement is not working on Windows

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes: #7

### CODE REVIEW

**Comment by tribou** [comment]
Awesome, thanks for sending this fix @alan-agius4!

It looks like I didn't have the "Build forked pull request branches" turned on in CircleCI, and there's a small lint issue. Could you please run `npm test` and fix the errors that come up?  Or, if you check the box in the right sidebar here to "Allow edits from maintainers," I'll be glad to do the fix and then merge.  Thanks again!

**Comment by alan-agius4** [comment]
Hey, thanks for looking into this. This box is already ticked.

Can you check again?

**Comment by tribou** [comment]
Deployed in patch v0.1.6

**Comment by alan-agius4** [comment]
thanks

**Pull request merged**
