### PR TITLE
Use Prettier

### PR DESCRIPTION
**Pull request by chrisblossom**
This adds [Prettier](https://prettier.io) to the project. I don't expect this to be merged but I thought I'd put a PR in case you liked it.

Used 4 spaces because of [your "but push towards better readability"](https://github.com/tribou/eslint-plugin-tribou) line.

Feel free to close.

### CODE REVIEW

**Comment by tribou** [comment]
Good suggestion. Haven't had time to review yet, but this is something I've been considering for a while.

**Comment by chrisblossom** [comment]
I updated this PR and removed the formatting changes so it can easily be merged at any point. If you decide to merge , please run ``npm run format`` on this branch and commit the formatting changes prior to merging.

This adds a git precommit hook that will format files on push.

**Comment by tribou** [comment]
I haven't forgotten about this... in fact, I have a frequent inner dialog debating the future direction for stylistic linting I should embrace. 😆 The contenders:

1) [Zero-configuration approach](https://github.com/prettier/prettier/issues/40#issue-199895633): just accept defaults for `prettier` as law because stylistic linting is subjective to the developer and opinions/exceptions around them often spark debates and distract developers from being productive. (i.e. follow in the path of `gofmt` and Golang)
2) Do (1) with the exception of trying to enforce ["the Good Parts"](http://jslint.com/help.html) where `prettier` may be lacking because of <ES5 compatibility. (i.e. because we're targeting ES5 or if we used babel, we can always add trailing commas to prevent accidental `prettier` parsing errors when editing arrays)
3) Don't pursue (1) but choose the `prettier` options that will get as close as possible to the existing stylistic lint configuration which has the goals of being sensitive to the Good Parts, git, vim, and whitespace-driven clarity (albeit subjectively).

And so far, the debate has just ended with:

¯\_(ツ)_/¯

**Comment by chrisblossom** [comment]
FYI, ``prettier`` [defaults](https://prettier.io/docs/en/options.html) are safe for ``es5``. I'm fairly certain in ``prettier v2``, ``es5`` will be the default for ``Trailing Commas``.

I've updated this PR to remove any conflicts with master.

**Comment by tribou** [comment]
Ah, interesting... well, perhaps we should just go with zero-configuration?

**Comment by chrisblossom** [comment]
I personally think you should find a config that you'd like to use for all of your projects and go with that. If that is zero-config, great! Just be warned, that means semi-colons (which I prefer), double quotes (until 2.0), and no trailing commas (until 2.0). I'd guess 90% of prettier users use single quotes and es5 trailing commas.

I'll update the PR to whatever you'd like. Just let me know.

[FYI, This is the config I use for my (compiled) projects.](https://github.com/chrisblossom/backtrack/blob/master/.prettierrc.js)

**Comment by chrisblossom** [comment]
Any final thoughts on this? I think using `prettier` is the important part, not the configuration of it. I'm good with whatever you decide.

**Comment by tribou** [comment]
Ah! meant to reply earlier but forgot... Didn't know about 2.0 prettier roadmap, so let's just go with the zero-config/default prettier options for now. When 2.0 rolls around, your `precommit` script will probably make that upgrade almost automatic. 💯

**Comment by chrisblossom** [comment]
Done! Ready to be merged.

**Pull request merged**
