### PR TITLE
Handle symlinks

### PR DESCRIPTION
**Pull request by chrisblossom**
I've seen this issue come up on create-react-app ([#648](https://github.com/facebook/create-react-app/pull/648) and [paths.js#L18](https://github.com/facebook/create-react-app/blob/2c34d5b66eab7d1c96e573bc48b8e82b6d8e82b0/packages/react-scripts/config/paths.js#L18)).

Not sure if wanted (seems maybe a bit over thinking/engineering), also not sure how to write tests.

### CODE REVIEW

**Comment by tribou** [comment]
Interesting catch on a potential issue. I could see symlinks being used in a CI environment, but we might just have to test locally on this one. Setup/teardown of creating/removing symlinks might get a bit dicey...

**Comment by chrisblossom** [comment]
I started adding tests to this and found it is getting complicated very quickly. I think if this is something to be supported we may need to rethink how we are matching paths.

[Here is where it starts getting complicated.](https://github.com/chrisblossom/jest-serializer-path/blob/4b4e8666fedb552dc412baa39367b2493b0eb837/lib/index_test.js#L414-L449)

I'm going to close this for now until someone actually runs into this issue. I won't delete my [WIP branch](https://github.com/chrisblossom/jest-serializer-path/tree/handle-symlinks) up for future reference.

**Comment by tribou** [comment]
Oh wow, no problem at all. Regardless, thanks for all of the other PRs to help make this package more robust!

**Comment by chrisblossom** [comment]
I just ran into this issue so I might try and solve it again. If you have any ideas a good please let me know.

**Comment by tribou** [comment]
Yikes... Is there a gist or small repo you could create to reproduce the issue? If I had some more context to better understand (like an example), I'd be glad to help solve.

**Comment by chrisblossom** [comment]
Do you use a mac for development?

**Comment by tribou** [comment]
Yes, I do nowadays

**Pull request closed without merging**
